import { Link } from 'react-router-dom'
import { useLang } from '../contexts/LanguageContext'

// **볼드** 텍스트를 처리하는 함수 (링크 자동 변환 방지)
function renderBoldText(text) {
  const parts = []
  const boldPattern = /\*\*(.+?)\*\*/g
  let lastIndex = 0
  let match

  while ((match = boldPattern.exec(text)) !== null) {
    // 볼드 앞 텍스트
    if (match.index > lastIndex) {
      parts.push({ type: 'text', content: text.substring(lastIndex, match.index) })
    }
    // 볼드 텍스트
    parts.push({ type: 'bold', content: match[1] })
    lastIndex = match.index + match[0].length
  }
  // 나머지 텍스트
  if (lastIndex < text.length) {
    parts.push({ type: 'text', content: text.substring(lastIndex) })
  }

  if (parts.length === 0) {
    return <span>{text}</span>
  }

  return (
    <span>
      {parts.map((part, idx) => {
        if (part.type === 'bold') {
          return <strong key={idx} className="font-bold">{part.content}</strong>
        }
        return <span key={idx}>{part.content}</span>
      })}
    </span>
  )
}

const CONTENT = {
  en: {
    title: "Terms of Service",
    lastUpdated: "Last updated: February 2026",
    sections: [
      {
        heading: "1. Introduction",
        paragraphs: [
          "Welcome to Your Pet Insight (\"we,\" \"our,\" or \"us\"). Your Pet Insight is an AI-powered dog personality analysis service available at yourpetinsight.com. Our service provides free basic personality results and premium detailed reports ($5.99) to help you better understand your pet's unique personality traits.",
          "By accessing or using our service, you agree to be bound by these Terms of Service (\"Terms\"). If you do not agree to these Terms, please do not use our service."
        ]
      },
      {
        heading: "2. Eligibility",
        paragraphs: [
          "You must be at least 14 years old to use this service. By using our service, you represent and warrant that you meet this age requirement.",
          "You may use our service without creating an account. However, an email address may be required for premium report purchases and delivery."
        ]
      },
      {
        heading: "3. Nature of Results",
        paragraphs: [
          "**IMPORTANT: Our personality analysis results are provided for entertainment and reference purposes only.**",
          "The results generated by our AI system are not intended to replace professional veterinary, behavioral, or training advice. Our service does not provide medical diagnoses, treatment recommendations, or professional behavioral assessments.",
          "We do not guarantee the accuracy, completeness, or reliability of any analysis or results. The AI-generated content is based on the information you provide and should be considered as a tool for exploration and entertainment rather than definitive guidance.",
          "You acknowledge that any decisions or actions you take based on our results are made at your own risk. We are not responsible for any consequences arising from the use or interpretation of our results."
        ]
      },
      {
        heading: "4. Premium Service",
        paragraphs: [
          "Our Premium Report is a one-time purchase ($5.99) and is not a subscription service. Each purchase provides access to a detailed AI-generated personality analysis report.",
          "Payments are processed through Polar, a third-party payment processor. By making a purchase, you agree to Polar's terms and conditions.",
          "For information about refunds, please refer to our Refund Policy."
        ]
      },
      {
        heading: "5. Data Retention and Deletion",
        paragraphs: [
          "**Your test result data will be automatically deleted 30 days after creation.**",
          "Once deleted, your results cannot be recovered. We strongly recommend that you save your results if you wish to access them after the 30-day period.",
          "To preserve your results:",
          "• Use the image save functionality available on the results screen to download or screenshot your results",
          "• If you purchase a Premium Report, a copy will be sent to the email address you provide during checkout",
          "For detailed information about data handling, please refer to our Privacy Policy."
        ]
      },
      {
        heading: "6. Intellectual Property",
        paragraphs: [
          "All content, designs, AI analysis results, and materials on our service are the property of Your Pet Insight and are protected by copyright and other intellectual property laws.",
          "You may use the results for personal, non-commercial purposes only. You may not reproduce, distribute, modify, or create derivative works from our content without our express written permission."
        ]
      },
      {
        heading: "7. Service Modifications and Discontinuation",
        paragraphs: [
          "We reserve the right to modify, suspend, or discontinue any part of our service at any time, with or without notice.",
          "We are not liable for any loss or damage resulting from such modifications, suspensions, or discontinuations."
        ]
      },
      {
        heading: "8. Disclaimer",
        paragraphs: [
          "Our service is provided \"AS IS\" and \"AS AVAILABLE\" without warranties of any kind, either express or implied.",
          "We do not warrant that our service will be uninterrupted, error-free, or free from viruses or other harmful components. We do not guarantee the accuracy, completeness, or usefulness of any information provided through our service."
        ]
      },
      {
        heading: "9. Limitation of Liability",
        paragraphs: [
          "To the maximum extent permitted by law, Your Pet Insight shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your use of our service."
        ]
      },
      {
        heading: "10. Contact Information",
        paragraphs: [
          "If you have any questions about these Terms of Service, please contact us at support@yourpetinsight.com."
        ]
      }
    ]
  },
  jp: {
    title: "利用規約",
    lastUpdated: "最終更新日: 2026年2月",
    sections: [
      {
        heading: "1. はじめに",
        paragraphs: [
          "Your Pet Insight（「当社」「私たち」または「弊社」）へようこそ。Your Pet Insightは、yourpetinsight.comで提供されるAIを活用した犬の性格分析サービスです。当サービスは、無料の基本性格結果とプレミアム詳細レポート（$5.99）を提供し、ペットのユニークな性格特性をより深く理解するお手伝いをします。",
          "当サービスにアクセスまたは使用することにより、本利用規約（「規約」）に同意したものとみなされます。本規約に同意しない場合は、当サービスを使用しないでください。"
        ]
      },
      {
        heading: "2. 利用資格",
        paragraphs: [
          "本サービスを利用するには、14歳以上である必要があります。当サービスを使用することにより、この年齢要件を満たしていることを表明し保証します。",
          "アカウントを作成せずに当サービスを利用できます。ただし、プレミアムレポートの購入および配信にはメールアドレスが必要な場合があります。"
        ]
      },
      {
        heading: "3. 結果の性質",
        paragraphs: [
          "**重要：当社の性格分析結果は、エンターテインメントおよび参考目的でのみ提供されます。**",
          "当社のAIシステムによって生成された結果は、専門的な獣医学、行動学、またはトレーニングのアドバイスを置き換えることを意図していません。当サービスは、医学的診断、治療推奨、または専門的な行動評価を提供しません。",
          "当社は、分析または結果の正確性、完全性、または信頼性を保証しません。AI生成コンテンツは、お客様が提供する情報に基づいており、確定的なガイダンスではなく、探索およびエンターテインメントのツールとして考慮されるべきです。",
          "お客様は、当社の結果に基づいて行う決定または行動は、お客様自身のリスクで行われることを承認します。当社は、当社の結果の使用または解釈から生じる結果について責任を負いません。"
        ]
      },
      {
        heading: "4. プレミアムサービス",
        paragraphs: [
          "当社のプレミアムレポートは、1回限りの購入（$5.99）であり、サブスクリプションサービスではありません。各購入により、詳細なAI生成性格分析レポートへのアクセスが提供されます。",
          "支払いは、第三者決済処理業者であるPolarを通じて処理されます。購入することにより、Polarの利用規約に同意したものとみなされます。",
          "返金に関する情報については、当社の返金ポリシーを参照してください。"
        ]
      },
      {
        heading: "5. データの保持および削除",
        paragraphs: [
          "**テスト結果データは、作成日から30日後に自動的に削除されます。**",
          "削除後、結果を復元することはできません。30日後も結果にアクセスしたい場合は、結果を保存することを強く推奨します。",
          "結果を保存するには：",
          "• 結果画面で利用可能な画像保存機能を使用して、結果をダウンロードまたはスクリーンショットする",
          "• プレミアムレポートを購入した場合、チェックアウト時に提供したメールアドレスにコピーが送信されます",
          "データ処理の詳細については、当社のプライバシーポリシーを参照してください。"
        ]
      },
      {
        heading: "6. 知的財産権",
        paragraphs: [
          "当サービス上のすべてのコンテンツ、デザイン、AI分析結果、および資料は、Your Pet Insightの財産であり、著作権およびその他の知的財産法によって保護されています。",
          "お客様は、個人的、非商業的目的でのみ結果を使用できます。当社の明示的な書面による許可なしに、当社のコンテンツを複製、配布、変更、または派生作品を作成することはできません。"
        ]
      },
      {
        heading: "7. サービスの変更および中止",
        paragraphs: [
          "当社は、事前の通知の有無にかかわらず、いつでも当サービスの一部を変更、一時停止、または中止する権利を留保します。",
          "当社は、そのような変更、一時停止、または中止から生じる損失または損害について責任を負いません。"
        ]
      },
      {
        heading: "8. 免責事項",
        paragraphs: [
          "当サービスは「現状のまま」「利用可能な状態で」提供され、明示または黙示を問わず、いかなる種類の保証もありません。",
          "当社は、当サービスが中断されない、エラーがない、またはウイルスやその他の有害なコンポーネントがないことを保証しません。当社は、当サービスを通じて提供される情報の正確性、完全性、または有用性を保証しません。"
        ]
      },
      {
        heading: "9. 責任の制限",
        paragraphs: [
          "法律で許可される最大限の範囲で、Your Pet Insightは、間接的、偶発的、特別、結果的、または懲罰的損害、または利益または収益の損失（直接的または間接的に発生したかどうかを問わず）、またはデータ、使用、のれん、またはその他の無形の損失について、当サービスの使用から生じる責任を負いません。"
        ]
      },
      {
        heading: "10. 連絡先",
        paragraphs: [
          "本利用規約に関するご質問がございましたら、support@yourpetinsight.comまでお問い合わせください。"
        ]
      }
    ]
  }
}

function TermsOfService() {
  const { lang } = useLang()
  const content = CONTENT[lang] || CONTENT.en

  return (
    <main className="min-h-screen bg-[#F9FBF9]">
      <div className="max-w-3xl mx-auto px-4 py-12 md:py-20">
        {/* 제목 */}
        <h1 className="text-3xl md:text-4xl font-display font-bold text-primary mb-2">
          {content.title}
        </h1>
        <p className="text-primary/50 text-sm mb-10">
          {content.lastUpdated}
        </p>

        {/* 본문 */}
        <div className="prose prose-lg prose-green max-w-none">
          {content.sections.map((section, i) => (
            <section key={i} className="mb-10">
              <h2 className="text-xl font-display font-bold text-primary mb-3">
                {section.heading}
              </h2>
              {section.paragraphs.map((p, j) => {
                // 빈 문자열 처리
                if (!p || p.trim() === '') {
                  return null
                }

                // 볼드 처리만 수행 (링크는 하단 섹션에서 제공)
                return (
                  <p key={j} className="text-[#2D3436]/80 leading-relaxed mb-4 text-[15px]">
                    {renderBoldText(p)}
                  </p>
                )
              })}
            </section>
          ))}
        </div>

        {/* 하단 링크 */}
        <div className="border-t border-primary/10 pt-8 mt-12 flex flex-wrap gap-6 text-sm text-primary/50">
          <Link to={`/${lang}/terms`} className="hover:text-primary transition-colors">
            {lang === 'jp' ? '利用規約' : 'Terms of Service'}
          </Link>
          <Link to={`/${lang}/privacy`} className="hover:text-primary transition-colors">
            {lang === 'jp' ? 'プライバシーポリシー' : 'Privacy Policy'}
          </Link>
          <Link to={`/${lang}/refund`} className="hover:text-primary transition-colors">
            {lang === 'jp' ? '返金ポリシー' : 'Refund Policy'}
          </Link>
        </div>
      </div>
    </main>
  )
}

export default TermsOfService

